
logging:
  config: classpath:logback.xml
server:
  port: 38080


spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # 其他数据库配置...
    url: jdbc:p6spy:mysql://192.168.99.100:3306/myproject?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  data:
    redis:
      database: 10
      host: 192.168.99.100
      port: 6379
      password: 123456

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: '测试'
      paths-to-match: '/**'
      packages-to-scan: com.example.controller
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

