server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # 其他数据库配置...
    url: jdbc:p6spy:mysql://192.168.99.103:3306/myblog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  data:
    redis:
      database: 10
      host: 192.168.99.103
      port: 6379
  profiles:
    active: dev
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
  mapper-locations: com.example.mapper/**/*Mapper.xml